server.port=8080

spring.application.name=teamflow-backend

spring.datasource.url=jdbc:postgresql://localhost:5432/teamflow_db
spring.datasource.username=postgres
spring.datasource.password=2001

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

app.jwt.secret=Y2hhbmdlLXRoaXMtc2VjcmV0LWtleS10by1hLXZlcnktbG9uZy1zZWN1cmUtc2VjcmV0LWtleS0yMDI0
app.jwt.access-token-expiration-ms=900000
app.jwt.refresh-token-expiration-ms=604800000

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=
spring.mail.password=
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB

app.file.upload-dir=uploads

spring.jpa.open-in-view=false
