server.port=8080

spring.application.name=teamflow-backend

spring.datasource.url=jdbc:postgresql://localhost:5432/teamflow_db
spring.datasource.username=PostgreSQL 18
spring.datasource.password=2001

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

app.jwt.secret=change-this-secret-key-to-a-very-long-secure-secret-key
app.jwt.access-token-expiration-ms=900000
app.jwt.refresh-token-expiration-ms=604800000
